services:
  - type: web
    name: tg-game-bot
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: game_bot
      - key: CHANNEL_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 8080
